apiVersion: skaffold/v1
kind: Config
metadata:
  name: workflows
deploy:
  kubectl:
    manifests:
    - k8s/workflows.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: discoenv/workflows
  local: {}
